apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-pv-claim
spec:
  storageClassName: "cstor-csi-disk"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
