# apiVersion: kustomize.config.k8s.io/v1beta1
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
namespace: web-flux
images:
  - name: bharamicrosystems/nginx
    newTag: v1
resource:
  - nginx.yaml
  - nginx-service.yaml
  - namespace.yaml
  
